/*
 * This source file was generated by the Gradle 'init' task
 */
package org.application;

import be.seeseemelk.mockbukkit.MockBukkit;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {

    private Library plugin;

    @BeforeMethod
    public void setUp() {
        MockBukkit.mock();                    // spins up a fake server
        plugin = MockBukkit.load(Library.class); // loads your plugin
    }

    @AfterMethod
    public void tearDown() {
        MockBukkit.unmock();                  // tears it down after each test
    }

    @Test
    public void pluginLoads() {
        assertNotNull(plugin, "Plugin should have loaded successfully");
    }
}