import java.net.URL

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
    maven("https://repo.dmulloy2.net/repository/public/")  // ProtocolLib
    mavenLocal()  // for NMS (spigot built via BuildTools)
}

dependencies {
    testImplementation("junit:junit:4.13")
    compileOnly("org.spigotmc:spigot-api:1.12.2-R0.1-SNAPSHOT")
    compileOnly("org.spigotmc:spigot:1.12.2-R0.1-SNAPSHOT")  // NMS access
    compileOnly("com.comphenix.protocol:ProtocolLib:4.4.0")   // ProtocolLib
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.jar {
    archiveFileName.set("BradPlugin-${project.version}.jar")
}

tasks.register("setupSpigot") {
    doLast {
        val buildToolsDir = file("${rootDir}/buildtools")
        buildToolsDir.mkdirs()

        val buildToolsJar = file("${buildToolsDir}/BuildTools.jar")

        // Download BuildTools
        if (!buildToolsJar.exists()) {
            println("Downloading BuildTools...")
            URL("https://hub.spigotmc.org/jenkins/job/BuildTools/199/artifact/target/BuildTools.jar")
                .openStream().use { input ->
                    buildToolsJar.outputStream().use { output ->
                        input.copyTo(output)
                    }
                }
        }

        // Run BuildTools
        println("Running BuildTools for 1.12.2...")
        exec {
            workingDir = buildToolsDir
            commandLine("java", "-jar", "BuildTools.jar", "--rev", "1.12.2")
        }

        println("Done! Spigot is now in your local Maven cache.")
    }
}