/*
 * This source file was generated by the Gradle 'init' task
 */
package org.application;

import org.bukkit.plugin.java.JavaPlugin;

public class Library extends JavaPlugin {

    @Override
    public void onEnable() {
        getLogger().info("Plugin should have loaded successfully!");
    }

    @Override
    public void onDisable() {
        getLogger().info("Plugin disabled.");
    }
}
