/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugin;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.ProtocolManager;
import org.bukkit.plugin.java.JavaPlugin;

public class Library extends JavaPlugin {

    @Override
    public void onEnable() {
        ProtocolManager protocolManager = ProtocolLibrary.getProtocolManager();
        KnockbackModule kbModule = new KnockbackModule(this, PacketType.Play.Server.ENTITY_VELOCITY);
        protocolManager.addPacketListener(kbModule);
        getLogger().info("BradPlugin enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("BradPlugin disabled!");
    }
}